name: 每天9点36分推送新股申购信息

on:
  schedule:
    # 每个交易日 9:36 爬取并推送当天新股申购、新上市股票信息 (北京时间 UTC+8)
    - cron: '36 1 * * 1-5' # UTC 1:36 = 北京时间 9:36

  # 允许手动触发
  workflow_dispatch:
    inputs:
      task:
        description: '选择要执行的任务'
        required: true
        type: choice
        options:
          - 'push_new_stock'				#推送新股申购和新上市股票信息  

jobs:
  # 9:36 AM：推送新股申购和新上市股票信息
  push_new_stock:
    if: ${{ (github.event_name == 'schedule' && contains(github.event.schedule, '36 1 * * 1-5')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install akshare baostock

      - name: Debug info
        run: |
          echo "Event schedule: ${{ github.event.schedule }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Input task: ${{ github.event.inputs.task }}"
      
      - name: Run strategy
        env:
          TASK: 'push_new_stock'
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          # 执行主程序
          echo "当前北京时间: $(date -u -d "+8 hours" '+%Y-%m-%d %H:%M')"
          python main.py
          
          # 提交数据变更到仓库
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "定时任务：推送新股信息 $(date +'%Y-%m-%d %H:%M')" || echo "更新失败：没有新股信息"
          git push origin main || echo "Failed to push changes"

      - name: Verify execution
        run: |
          echo "北京时间9点36分推送新股信息到微信任务完成!"

