name: 每天9点36分推送新股申购信息

on:
  schedule:
    # 每个交易日 9:36 爬取并推送（UTC 1:36 = 北京时间 9:36）
    - cron: '36 1 * * 1-5'

  # 允许手动触发
  workflow_dispatch:
    inputs:
      task:
        description: '选择要执行的任务'
        required: true
        type: choice
        options:
          - 'push_new_stock'  # 推送新股申购和新上市股票信息  
          - 'test_message'    # 发送测试消息

jobs:
  run_task:
    # 条件：允许定时任务触发，或手动选择对应任务时触发
    if: ${{ (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'push_new_stock') || (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'test_message') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Debug info
        run: |
          echo "事件名称: ${{ github.event_name }}"
          echo "定时表达式: ${{ github.event.schedule || '无' }}"
          echo "手动任务选择: ${{ github.event.inputs.task || '无' }}"
          echo "当前UTC时间: $(date '+%Y-%m-%d %H:%M')"
          echo "当前北京时间: $(date -u -d "+8 hours" '+%Y-%m-%d %H:%M')"
      
      - name: Run task
        env:
          TASK: ${{ github.event.inputs.task || 'push_new_stock' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          python main.py
          
          # 提交数据变更
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "定时任务：更新新股信息 $(date +'%Y-%m-%d %H:%M')" || echo "无新股信息更新"
          git push origin main || echo "推送变更失败"

      - name: Task completed
        run: |
          echo "任务执行完成!"
