name: 新股信息定时推送任务

on:
  schedule:
    # 交易日北京时间9:36触发（UTC+8，对应UTC 1:36）
    - cron: '36 1 * * 1-5'

  # 手动触发（支持正常推送/测试推送）
  workflow_dispatch:
    inputs:
      task:
        description: '选择任务类型'
        required: true
        type: choice
        options:
          - 'push_new_stock'  # 正常推送（仅当天数据，非交易日跳过）
          - 'test_push'       # 测试推送（无数据回溯21天，忽略交易日判断）

jobs:
  run_stock_task:
    # 触发条件：定时任务 或 手动选择对应任务
    if: ${{ 
      (github.event_name == 'schedule') || 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'push_new_stock') || 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'test_push') 
    }}
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 用于提交推送标记文件到仓库

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # 拉取完整历史（避免git push失败）

      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 稳定兼容版本
          cache: 'pip'            # 缓存依赖，加速安装

      - name: 安装依赖包
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 输出调试信息（方便排查问题）
        run: |
          echo "===== 调试信息 ====="
          echo "事件类型: ${{ github.event_name }}"
          echo "定时表达式: ${{ github.event.schedule || '无' }}"
          echo "手动选择任务: ${{ github.event.inputs.task || '无' }}"
          echo "当前UTC时间: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "当前北京时间: $(date -u -d "+8 hours" '+%Y-%m-%d %H:%M:%S')"
          echo "测试模式标记: ${{ github.event.inputs.task == 'test_push' }}"
          echo "===================="

      - name: 执行爬取推送任务
        env:
          # 传递任务类型（定时任务默认push_new_stock）
          TASK: ${{ github.event.inputs.task || 'push_new_stock' }}
          # 传递测试模式标记（true=测试回溯，false=正常模式）
          TEST_MODE: ${{ github.event.inputs.task == 'test_push' }}
          # 企业微信Webhook（从GitHub Secrets获取，避免硬编码）
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          python main.py

      - name: 提交推送标记文件（避免重复推送）
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 检查是否有数据变更
          if git status | grep -q "data/flags/"; then
            git add data/flags/
            git commit -m "添加推送标记: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
            echo "推送标记已提交到仓库"
          else
            echo "无新的推送标记需要提交"
          fi

      - name: 任务执行完成
        run: |
          echo "任务执行结束！"
