name: 新股信息推送任务

on:
  schedule:
    # 每个交易日 9:36 爬取并推送当天数据（UTC 1:36 = 北京时间 9:36）
    - cron: '36 1 * * 1-5'

  # 允许手动触发（支持测试模式）
  workflow_dispatch:
    inputs:
      task:
        description: '选择任务类型'
        required: true
        type: choice
        options:
          - 'push_new_stock'  # 正常推送（仅当天数据）
          - 'test_push'       # 测试推送（无数据则回溯21天）

jobs:
  run_task:
    # 条件：定时任务或手动选择对应任务时触发
    if: ${{ (github.event_name == 'schedule') || 
            (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'push_new_stock') || 
            (github.event_name == 'workflow_dispatch' && github.event.inputs.task == 'test_push') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Debug info
        run: |
          echo "事件名称: ${{ github.event_name }}"
          echo "定时表达式: ${{ github.event.schedule || '无' }}"
          echo "手动任务选择: ${{ github.event.inputs.task || '无' }}"
          echo "当前UTC时间: $(date '+%Y-%m-%d %H:%M')"
          echo "当前北京时间: $(date -u -d "+8 hours" '+%Y-%m-%d %H:%M')"
      
      - name: Run task
        env:
          # 传递任务类型
          TASK: ${{ github.event.inputs.task || 'push_new_stock' }}
          # 传递测试模式标记（关键：手动测试时为true）
          TEST_MODE: ${{ github.event.inputs.task == 'test_push' }}
          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        run: |
          python main.py
          
          # 提交数据变更
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "任务更新: $(date +'%Y-%m-%d %H:%M')" || echo "无数据更新"
          git push origin main || echo "推送变更失败"

      - name: Task completed
        run: |
          echo "任务执行完成!"
